### ISSUE TITLE
KeyError: 'my_database'

### ISSUE THREAD

**Issue by garthk** [simonw/datasette-init#3]
> Any tables that do not yet exist will be created when Datasette first starts.

Implicit, but easy to miss if you're a beginner: any _databases_ that do not yet exist will cause a traceback.

Using the `manifest.json` contents from the README and datasette 0.63.3:

```plain
$ datasette serve .
Traceback (most recent call last):
  File ".direnv/python-3.9.6/lib/python3.9/site-packages/datasette_init/__init__.py", line 12, in inner
    database = datasette.get_database(database_name)
  File ".direnv/python-3.9.6/lib/python3.9/site-packages/datasette/app.py", line 423, in get_database
    return self.databases[name]
KeyError: 'my_database'
```

Not sure if you'd prefer to treat it as a doc problem, or a bug, or PEBCAK.

**Comment by garthk** [comment]
Workaround: 

```bash
touch my_database.db
datasette serve .
```
